name: "UTBot code analysis"
description: "UTBot code analysis allows adding tests and code analysis information by pull request"
branding:
  icon: 'terminal'
  color: 'blue'

on:
  inputs:
    test_push_info:
      description: 'Do tests need to be pushed'
      required: true
    test_delete_info:
      description: 'Do old tests need to be deleted'
      required: true
    utbot_version:
      description: 'UTBot version'
      required: true
    launch_param:
      description: 'Run utbot to all project, directory or file'
      required: true
    param_name:
      description: 'directory or file name'
      required: true
    
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Delete old tests
      if: ${{ inputs.test_delete_info == 'true' }}
      uses: EndBug/add-and-commit@v9
      with:
        remove: 'tests'
        author_name: 'github-actions[utbot]'
        message: 'UTBot code analysis delete old tests'
        
    - name: Download server executable
      run: |
           mkdir "utbot-release-${{ inputs.utbot_version }}"
           wget "https://github.com/olezhabobrov/UTBotCpp/releases/download/v${{ inputs.utbot_version }}/utbot-release-${{ inputs.utbot_version }}.zip" -P "./utbot-release-${{ inputs.utbot_version }}"
           unzip "./utbot-release-${{ inputs.utbot_version }}/utbot-release-${{ inputs.utbot_version }}.zip" -d "./utbot-release-${{ inputs.utbot_version }}/"
           chmod +x "./utbot-release-${{ inputs.utbot_version }}/unpack_and_run_utbot.sh"
           cd "./utbot-release-${{ inputs.utbot_version }}" && ./unpack_and_run_utbot.sh
      shell: sh
           
    - name: Testing project
      if: ${{ inputs.launch_param == 'project' }}
      run: |       
          cd "./utbot-release-${{ inputs.utbot_version }}/utbot_distr"
          export CURRENT_FOLDER="$( cd $( dirname . ) && pwd )"
          RUN_SYSTEM_SCRIPT_PATH=$CURRENT_FOLDER/utbot_run_system.sh
          UTBOT_CLI_OPTIONS="generate --project-path ../.. project"
          $RUN_SYSTEM_SCRIPT_PATH "cli" $UTBOT_CLI_OPTIONS
      shell: sh
      
    - name: Testing file
      if: ${{ inputs.launch_param == 'file' }}
      run: |       
          cd "./utbot-release-${{ inputs.utbot_version }}/utbot_distr"
          export CURRENT_FOLDER="$( cd $( dirname . ) && pwd )"
          RUN_SYSTEM_SCRIPT_PATH=$CURRENT_FOLDER/utbot_run_system.sh
          UTBOT_CLI_OPTIONS="generate --project-path ../.. file --file-path ../../${{ inputs.param_name }}"
          $RUN_SYSTEM_SCRIPT_PATH "cli" $UTBOT_CLI_OPTIONS
      shell: sh
      
    - name: Testing file
      if: ${{ inputs.launch_param == 'directory' }}
      run: |       
          cd "./utbot-release-${{ inputs.utbot_version }}/utbot_distr"
          export CURRENT_FOLDER="$( cd $( dirname . ) && pwd )"
          RUN_SYSTEM_SCRIPT_PATH=$CURRENT_FOLDER/utbot_run_system.sh
          UTBOT_CLI_OPTIONS="generate --project-path ../../${{ inputs.param_name }} folder --folder-path ../../${{ inputs.param_name }}"
          $RUN_SYSTEM_SCRIPT_PATH "cli" $UTBOT_CLI_OPTIONS
          ls
      shell: sh
      
    - name: Create Pull Request with tests and codeAnalysis information
      uses: peter-evans/create-pull-request@v4
      if: ${{ inputs.test_push_info == 'true' }}
      with:
        add-paths: |
            tests/
            codeAnalysis/
        commit-message: UTBot code analysis add tests and codeAnalysis information
        branch-suffix: short-commit-hash
        branch: utbote-code-analysis
        title: UTBot code analysis
        body: UTBot code analysis add tests and codeAnalysis information
        delete-branch: true
        
    - name: Create Pull Request with tests and codeAnalysis information
      uses: peter-evans/create-pull-request@v4
      if: ${{ inputs.test_push_info != 'true' }}
      with:
        add-paths: |
            codeAnalysis/
        commit-message: UTBot code analysis add tests and codeAnalysis information
        branch-suffix: short-commit-hash
        branch: utbote-code-analysis
        title: UTBot code analysis
        body: UTBot code analysis add tests and codeAnalysis information
        delete-branch: true
        
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeAnalysis/project_code_analysis.sarif
